language: python
python:
  - "3.6"
install:
  - python -m venv venv
  - . venv/bin/activate
  - pip install -r requirements.txt
script:
  - . venv/bin/activate
  - flake8 --exclude=venv* --statistics
  - pytest -v --cov=calculator
